// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
)

const blockNumber = `-- name: BlockNumber :one
SELECT
    block_number
FROM
    blocks
ORDER BY
    block_number DESC
LIMIT
    1
`

func (q *Queries) BlockNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, blockNumber)
	var block_number int64
	err := row.Scan(&block_number)
	return block_number, err
}

const blockNumberByHash = `-- name: BlockNumberByHash :one
SELECT
    block_number
FROM
    blocks
WHERE
    block_hash = ?
LIMIT
    1
`

func (q *Queries) BlockNumberByHash(ctx context.Context, blockHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, blockNumberByHash, blockHash)
	var block_number int64
	err := row.Scan(&block_number)
	return block_number, err
}

const getBlockByHash = `-- name: GetBlockByHash :one
SELECT
    block_number, block_hash, parent_hash, state_root, timestamp, extra_data
FROM
    blocks
WHERE
    block_hash = ?
`

func (q *Queries) GetBlockByHash(ctx context.Context, blockHash []byte) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlockByHash, blockHash)
	var i Block
	err := row.Scan(
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.StateRoot,
		&i.Timestamp,
		&i.ExtraData,
	)
	return i, err
}

const getBlockByNumber = `-- name: GetBlockByNumber :one
SELECT
    block_number, block_hash, parent_hash, state_root, timestamp, extra_data
FROM
    blocks
WHERE
    block_number = ?
`

func (q *Queries) GetBlockByNumber(ctx context.Context, blockNumber int64) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlockByNumber, blockNumber)
	var i Block
	err := row.Scan(
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.StateRoot,
		&i.Timestamp,
		&i.ExtraData,
	)
	return i, err
}

const getBlockTxCountByHash = `-- name: GetBlockTxCountByHash :one
SELECT
    COUNT(*) AS tx_count
FROM
    transactions t
    JOIN blocks b ON t.block_number = b.block_number
WHERE
    b.block_hash = ?
`

func (q *Queries) GetBlockTxCountByHash(ctx context.Context, blockHash []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockTxCountByHash, blockHash)
	var tx_count int64
	err := row.Scan(&tx_count)
	return tx_count, err
}

const getBlockTxCountByNumber = `-- name: GetBlockTxCountByNumber :one
SELECT
    COUNT(*) AS tx_count
FROM
    transactions
WHERE
    block_number = ?
`

func (q *Queries) GetBlockTxCountByNumber(ctx context.Context, blockNumber int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlockTxCountByNumber, blockNumber)
	var tx_count int64
	err := row.Scan(&tx_count)
	return tx_count, err
}

const getFullTransactionByHash = `-- name: GetFullTransactionByHash :one
SELECT
    tx_hash, block_hash, block_number, tx_index, raw_tx, from_address, to_address, contract_address, status, fabric_tx_id, fabric_tx_status
FROM
    transactions
WHERE
    tx_hash = ?
LIMIT
    1
`

func (q *Queries) GetFullTransactionByHash(ctx context.Context, txHash []byte) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getFullTransactionByHash, txHash)
	var i Transaction
	err := row.Scan(
		&i.TxHash,
		&i.BlockHash,
		&i.BlockNumber,
		&i.TxIndex,
		&i.RawTx,
		&i.FromAddress,
		&i.ToAddress,
		&i.ContractAddress,
		&i.Status,
		&i.FabricTxID,
		&i.FabricTxStatus,
	)
	return i, err
}

const getLogsByTxHash = `-- name: GetLogsByTxHash :many
SELECT
    block_number, block_hash, tx_hash, tx_index, log_index, address, topic0, topic1, topic2, topic3, data
FROM
    logs
WHERE
    tx_hash = ?
ORDER BY
    log_index
`

func (q *Queries) GetLogsByTxHash(ctx context.Context, txHash []byte) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, getLogsByTxHash, txHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Log
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.BlockNumber,
			&i.BlockHash,
			&i.TxHash,
			&i.TxIndex,
			&i.LogIndex,
			&i.Address,
			&i.Topic0,
			&i.Topic1,
			&i.Topic2,
			&i.Topic3,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByBlockHashAndIndex = `-- name: GetTransactionByBlockHashAndIndex :one
SELECT
    tx_hash, block_hash, block_number, tx_index, raw_tx, from_address, to_address, contract_address, status, fabric_tx_id, fabric_tx_status
FROM
    transactions
WHERE
    block_hash = ?
    AND tx_index = ?
LIMIT
    1
`

type GetTransactionByBlockHashAndIndexParams struct {
	BlockHash []byte
	TxIndex   int64
}

func (q *Queries) GetTransactionByBlockHashAndIndex(ctx context.Context, arg GetTransactionByBlockHashAndIndexParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByBlockHashAndIndex, arg.BlockHash, arg.TxIndex)
	var i Transaction
	err := row.Scan(
		&i.TxHash,
		&i.BlockHash,
		&i.BlockNumber,
		&i.TxIndex,
		&i.RawTx,
		&i.FromAddress,
		&i.ToAddress,
		&i.ContractAddress,
		&i.Status,
		&i.FabricTxID,
		&i.FabricTxStatus,
	)
	return i, err
}

const getTransactionByBlockNumberAndIndex = `-- name: GetTransactionByBlockNumberAndIndex :one
SELECT
    tx_hash, block_hash, block_number, tx_index, raw_tx, from_address, to_address, contract_address, status, fabric_tx_id, fabric_tx_status
FROM
    transactions
WHERE
    block_number = ?
    AND tx_index = ?
LIMIT
    1
`

type GetTransactionByBlockNumberAndIndexParams struct {
	BlockNumber int64
	TxIndex     int64
}

func (q *Queries) GetTransactionByBlockNumberAndIndex(ctx context.Context, arg GetTransactionByBlockNumberAndIndexParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByBlockNumberAndIndex, arg.BlockNumber, arg.TxIndex)
	var i Transaction
	err := row.Scan(
		&i.TxHash,
		&i.BlockHash,
		&i.BlockNumber,
		&i.TxIndex,
		&i.RawTx,
		&i.FromAddress,
		&i.ToAddress,
		&i.ContractAddress,
		&i.Status,
		&i.FabricTxID,
		&i.FabricTxStatus,
	)
	return i, err
}

const getTransactionByHash = `-- name: GetTransactionByHash :one
SELECT
    tx_hash, block_hash, block_number, tx_index, raw_tx, from_address, to_address, contract_address, status, fabric_tx_id, fabric_tx_status
FROM
    transactions
WHERE
    tx_hash = ?
LIMIT
    1
`

func (q *Queries) GetTransactionByHash(ctx context.Context, txHash []byte) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByHash, txHash)
	var i Transaction
	err := row.Scan(
		&i.TxHash,
		&i.BlockHash,
		&i.BlockNumber,
		&i.TxIndex,
		&i.RawTx,
		&i.FromAddress,
		&i.ToAddress,
		&i.ContractAddress,
		&i.Status,
		&i.FabricTxID,
		&i.FabricTxStatus,
	)
	return i, err
}

const getTransactionsByBlockHash = `-- name: GetTransactionsByBlockHash :many
SELECT
    t.tx_hash, t.block_hash, t.block_number, t.tx_index, t.raw_tx, t.from_address, t.to_address, t.contract_address, t.status, t.fabric_tx_id, t.fabric_tx_status
FROM
    transactions t
    JOIN blocks b ON t.block_number = b.block_number
WHERE
    b.block_hash = ?
ORDER BY
    t.tx_index ASC
`

func (q *Queries) GetTransactionsByBlockHash(ctx context.Context, blockHash []byte) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByBlockHash, blockHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHash,
			&i.BlockNumber,
			&i.TxIndex,
			&i.RawTx,
			&i.FromAddress,
			&i.ToAddress,
			&i.ContractAddress,
			&i.Status,
			&i.FabricTxID,
			&i.FabricTxStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsByBlockNumber = `-- name: GetTransactionsByBlockNumber :many
SELECT
    tx_hash, block_hash, block_number, tx_index, raw_tx, from_address, to_address, contract_address, status, fabric_tx_id, fabric_tx_status
FROM
    transactions
WHERE
    block_number = ?
ORDER BY
    tx_index ASC
`

func (q *Queries) GetTransactionsByBlockNumber(ctx context.Context, blockNumber int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsByBlockNumber, blockNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.TxHash,
			&i.BlockHash,
			&i.BlockNumber,
			&i.TxIndex,
			&i.RawTx,
			&i.FromAddress,
			&i.ToAddress,
			&i.ContractAddress,
			&i.Status,
			&i.FabricTxID,
			&i.FabricTxStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO
    blocks (
        block_number,
        block_hash,
        parent_hash,
        state_root,
        timestamp,
        extra_data
    )
VALUES
    (?, ?, ?, ?, ?, ?) ON CONFLICT (block_number) DO NOTHING
`

type InsertBlockParams struct {
	BlockNumber int64
	BlockHash   []byte
	ParentHash  []byte
	StateRoot   []byte
	Timestamp   int64
	ExtraData   []byte
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertBlock,
		arg.BlockNumber,
		arg.BlockHash,
		arg.ParentHash,
		arg.StateRoot,
		arg.Timestamp,
		arg.ExtraData,
	)
	return err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO
    logs (
        block_number,
        block_hash,
        tx_hash,
        tx_index,
        log_index,
        address,
        topic0,
        topic1,
        topic2,
        topic3,
        data
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (tx_hash, log_index) DO UPDATE SET
        block_number = excluded.block_number,
        block_hash = excluded.block_hash,
        tx_index = excluded.tx_index,
        address = excluded.address,
        topic0 = excluded.topic0,
        topic1 = excluded.topic1,
        topic2 = excluded.topic2,
        topic3 = excluded.topic3,
        data = excluded.data
`

type InsertLogParams struct {
	BlockNumber int64
	BlockHash   []byte
	TxHash      []byte
	TxIndex     int64
	LogIndex    int64
	Address     []byte
	Topic0      []byte
	Topic1      []byte
	Topic2      []byte
	Topic3      []byte
	Data        []byte
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.ExecContext(ctx, insertLog,
		arg.BlockNumber,
		arg.BlockHash,
		arg.TxHash,
		arg.TxIndex,
		arg.LogIndex,
		arg.Address,
		arg.Topic0,
		arg.Topic1,
		arg.Topic2,
		arg.Topic3,
		arg.Data,
	)
	return err
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO
    transactions (
        tx_hash,
        block_hash,
        block_number,
        tx_index,
        raw_tx,
        from_address,
        to_address,
        contract_address,
        status,
        fabric_tx_id,
        fabric_tx_status
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (tx_hash) DO UPDATE SET
        block_hash = excluded.block_hash,
        block_number = excluded.block_number,
        tx_index = excluded.tx_index,
        raw_tx = excluded.raw_tx,
        from_address = excluded.from_address,
        to_address = excluded.to_address,
        contract_address = excluded.contract_address,
        status = excluded.status,
        fabric_tx_id = excluded.fabric_tx_id,
        fabric_tx_status = excluded.fabric_tx_status
`

type InsertTransactionParams struct {
	TxHash          []byte
	BlockHash       []byte
	BlockNumber     int64
	TxIndex         int64
	RawTx           []byte
	FromAddress     []byte
	ToAddress       []byte
	ContractAddress []byte
	Status          int64
	FabricTxID      string
	FabricTxStatus  int64
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertTransaction,
		arg.TxHash,
		arg.BlockHash,
		arg.BlockNumber,
		arg.TxIndex,
		arg.RawTx,
		arg.FromAddress,
		arg.ToAddress,
		arg.ContractAddress,
		arg.Status,
		arg.FabricTxID,
		arg.FabricTxStatus,
	)
	return err
}

const latestBlock = `-- name: LatestBlock :one
SELECT
    block_number, block_hash, parent_hash, state_root, timestamp, extra_data
FROM
    blocks
ORDER BY
    block_number DESC
LIMIT
    1
`

func (q *Queries) LatestBlock(ctx context.Context) (Block, error) {
	row := q.db.QueryRowContext(ctx, latestBlock)
	var i Block
	err := row.Scan(
		&i.BlockNumber,
		&i.BlockHash,
		&i.ParentHash,
		&i.StateRoot,
		&i.Timestamp,
		&i.ExtraData,
	)
	return i, err
}
